import { writeFile } from 'node:fs/promises';
const id = 30344;
const url = `https://www.gutenberg.org/files/${id}/${id}-0.txt`;
console.log('fetching from', url);
const res = await fetch(url);
console.log('status:', res.status);
let text = await res.text();
const start = text.search(/\*\*\* ?START OF.*\*\*\*/);
const end = text.search(/\*\*\* ?END OF.*\*\*\*/);
if (start !== -1 && end !== -1) text = text.slice(text.indexOf('\n', start), end);
await writeFile('public/corpus/roxana.txt', text.trim());
console.log('wrote', text.length, 'chars');
console.log('first 300 chars:', text.slice(0, 300));
